version: '3.8'

networks:
  nginx-php-mysql-node:

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - 'certs:/etc/nginx/certs:ro'
      - 'vhostd:/etc/nginx/vhost.d'
      - 'html:/usr/share/nginx/html'
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - nginx-php-mysql-node
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
    volumes:
      - 'certs:/etc/nginx/certs:rw'
      - 'vhostd:/etc/nginx/vhost.d'
      - 'html:/usr/share/nginx/html'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
  
  nginx-service:
    image: nginx:alpine
    container_name: nginx-container
    expose:
      - '80'
    volumes:
      - './www:/var/www/project'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    environment:
      - 'VIRTUAL_HOST=localhost' #your domain
      - 'LETSENCRYPT_HOST=localhost' #your domain
      - 'LETSENCRYPT_EMAIL=your@email.com'
    depends_on:
      - nginx-proxy
      - letsencrypt
      - php-service
    networks:
      - nginx-php-mysql-node

  php-service:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    container_name: php-container
    expose:
      - '9000'
    volumes:
      - './www:/var/www/project'
    user: ${USER_ID}
    networks:
      - nginx-php-mysql-node

  ws-service:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    container_name: ws-container
    expose:
      - '80'
    volumes:
      - './ws:/var/www/project'
    user: ${USER_ID}
    networks:
      - nginx-php-mysql-node
    environment:
    - 'VIRTUAL_HOST=ws.localhost' #your domain
    - 'LETSENCRYPT_HOST=ws.localhost' #your domain
    - 'LETSENCRYPT_EMAIL=your@email.com'

  mysql-service:
    image: mysql:8
    container_name: mysql-container
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
    user: ${USER_ID}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db
    networks:
      - nginx-php-mysql-node

  node-service:
    image: node:lts-alpine
    container_name: node-container
    volumes:
      - ./www:/var/www/project
    user: ${USER_ID}
    working_dir: /var/www/project
    stdin_open: true
    networks:
      - nginx-php-mysql-node

volumes:
  certs: null
  html: null
  vhostd: null
