version: '3.8'

services:

  wsnginx-service:
    image: nginx:alpine
    container_name: wsnginx-container
    volumes:
      - './wsnginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './www:/var/www/project'
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - php-service
    network_mode: host

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  ws-service:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    container_name: ws-container
    ports:
      - '8080:8080'
    volumes:
      - './ws:/var/www/project'

  php-service:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    container_name: php-container
    ports:
      - '9000:9000'
    volumes:
      - './www:/var/www/project'
    user: ${USER_ID}

volumes:
  certs: null
  html: null
  vhostd: null
